// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.31.1
// source: RCRSProto.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface MessageProto {
  urn: number;
  components: { [key: number]: MessageComponentProto };
}

export interface MessageProto_ComponentsEntry {
  key: number;
  value?: MessageComponentProto | undefined;
}

export interface MessageListProto {
  commands: MessageProto[];
}

export interface MessageComponentProto {
  changeSet?: ChangeSetProto | undefined;
  commandList?: MessageListProto | undefined;
  config?: ConfigProto | undefined;
  entity?: EntityProto | undefined;
  entityID?: number | undefined;
  entityIDList?: IntListProto | undefined;
  entityList?: EntityListProto | undefined;
  floatList?: FloatListProto | undefined;
  intValue?: number | undefined;
  intList?: IntListProto | undefined;
  rawData?: Uint8Array | undefined;
  stringValue?: string | undefined;
  stringList?: StrListProto | undefined;
}

export interface StrListProto {
  values: string[];
}

export interface IntListProto {
  values: number[];
}

export interface FloatListProto {
  values: number[];
}

export interface IntMatrixProto {
  values: IntListProto[];
}

export interface ValueProto {
  defined: boolean;
  intValue?: number | undefined;
  boolValue?: boolean | undefined;
  doubleValue?: number | undefined;
  byteList?: Uint8Array | undefined;
  intList?: IntListProto | undefined;
  intMatrix?: IntMatrixProto | undefined;
  edgeList?: EdgeListProto | undefined;
  point2D?: Point2DProto | undefined;
}

export interface PropertyProto {
  urn: number;
  defined: boolean;
  intValue?: number | undefined;
  boolValue?: boolean | undefined;
  doubleValue?: number | undefined;
  byteList?: Uint8Array | undefined;
  intList?: IntListProto | undefined;
  intMatrix?: IntMatrixProto | undefined;
  edgeList?: EdgeListProto | undefined;
  point2D?: Point2DProto | undefined;
}

export interface Point2DProto {
  X: number;
  Y: number;
}

export interface EntityProto {
  urn: number;
  entityID: number;
  properties: PropertyProto[];
}

export interface EntityListProto {
  entities: EntityProto[];
}

export interface ConfigProto {
  data: { [key: string]: string };
}

export interface ConfigProto_DataEntry {
  key: string;
  value: string;
}

export interface EdgeListProto {
  edges: EdgeProto[];
}

export interface EdgeProto {
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  neighbour: number;
}

export interface ChangeSetProto {
  changes: ChangeSetProto_EntityChangeProto[];
  deletes: number[];
}

export interface ChangeSetProto_EntityChangeProto {
  entityID: number;
  urn: number;
  properties: PropertyProto[];
}

function createBaseMessageProto(): MessageProto {
  return { urn: 0, components: {} };
}

export const MessageProto: MessageFns<MessageProto> = {
  encode(message: MessageProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.urn !== 0) {
      writer.uint32(8).int32(message.urn);
    }
    globalThis.Object.entries(message.components).forEach(([key, value]: [string, MessageComponentProto]) => {
      MessageProto_ComponentsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.urn = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = MessageProto_ComponentsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.components[entry2.key] = entry2.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageProto>, I>>(base?: I): MessageProto {
    return MessageProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageProto>, I>>(object: I): MessageProto {
    const message = createBaseMessageProto();
    message.urn = object.urn ?? 0;
    message.components = (globalThis.Object.entries(object.components ?? {}) as [string, MessageComponentProto][])
      .reduce((acc: { [key: number]: MessageComponentProto }, [key, value]: [string, MessageComponentProto]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = MessageComponentProto.fromPartial(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseMessageProto_ComponentsEntry(): MessageProto_ComponentsEntry {
  return { key: 0, value: undefined };
}

export const MessageProto_ComponentsEntry: MessageFns<MessageProto_ComponentsEntry> = {
  encode(message: MessageProto_ComponentsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== undefined) {
      MessageComponentProto.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageProto_ComponentsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageProto_ComponentsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = MessageComponentProto.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageProto_ComponentsEntry>, I>>(base?: I): MessageProto_ComponentsEntry {
    return MessageProto_ComponentsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageProto_ComponentsEntry>, I>>(object: I): MessageProto_ComponentsEntry {
    const message = createBaseMessageProto_ComponentsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? MessageComponentProto.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseMessageListProto(): MessageListProto {
  return { commands: [] };
}

export const MessageListProto: MessageFns<MessageListProto> = {
  encode(message: MessageListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.commands) {
      MessageProto.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commands.push(MessageProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageListProto>, I>>(base?: I): MessageListProto {
    return MessageListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageListProto>, I>>(object: I): MessageListProto {
    const message = createBaseMessageListProto();
    message.commands = object.commands?.map((e) => MessageProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMessageComponentProto(): MessageComponentProto {
  return {
    changeSet: undefined,
    commandList: undefined,
    config: undefined,
    entity: undefined,
    entityID: undefined,
    entityIDList: undefined,
    entityList: undefined,
    floatList: undefined,
    intValue: undefined,
    intList: undefined,
    rawData: undefined,
    stringValue: undefined,
    stringList: undefined,
  };
}

export const MessageComponentProto: MessageFns<MessageComponentProto> = {
  encode(message: MessageComponentProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.changeSet !== undefined) {
      ChangeSetProto.encode(message.changeSet, writer.uint32(10).fork()).join();
    }
    if (message.commandList !== undefined) {
      MessageListProto.encode(message.commandList, writer.uint32(18).fork()).join();
    }
    if (message.config !== undefined) {
      ConfigProto.encode(message.config, writer.uint32(26).fork()).join();
    }
    if (message.entity !== undefined) {
      EntityProto.encode(message.entity, writer.uint32(34).fork()).join();
    }
    if (message.entityID !== undefined) {
      writer.uint32(40).int32(message.entityID);
    }
    if (message.entityIDList !== undefined) {
      IntListProto.encode(message.entityIDList, writer.uint32(50).fork()).join();
    }
    if (message.entityList !== undefined) {
      EntityListProto.encode(message.entityList, writer.uint32(58).fork()).join();
    }
    if (message.floatList !== undefined) {
      FloatListProto.encode(message.floatList, writer.uint32(66).fork()).join();
    }
    if (message.intValue !== undefined) {
      writer.uint32(72).int32(message.intValue);
    }
    if (message.intList !== undefined) {
      IntListProto.encode(message.intList, writer.uint32(82).fork()).join();
    }
    if (message.rawData !== undefined) {
      writer.uint32(90).bytes(message.rawData);
    }
    if (message.stringValue !== undefined) {
      writer.uint32(98).string(message.stringValue);
    }
    if (message.stringList !== undefined) {
      StrListProto.encode(message.stringList, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageComponentProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageComponentProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.changeSet = ChangeSetProto.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.commandList = MessageListProto.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.config = ConfigProto.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.entity = EntityProto.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.entityID = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.entityIDList = IntListProto.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.entityList = EntityListProto.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.floatList = FloatListProto.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.intValue = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.intList = IntListProto.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.rawData = reader.bytes();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.stringValue = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.stringList = StrListProto.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageComponentProto>, I>>(base?: I): MessageComponentProto {
    return MessageComponentProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageComponentProto>, I>>(object: I): MessageComponentProto {
    const message = createBaseMessageComponentProto();
    message.changeSet = (object.changeSet !== undefined && object.changeSet !== null)
      ? ChangeSetProto.fromPartial(object.changeSet)
      : undefined;
    message.commandList = (object.commandList !== undefined && object.commandList !== null)
      ? MessageListProto.fromPartial(object.commandList)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? ConfigProto.fromPartial(object.config)
      : undefined;
    message.entity = (object.entity !== undefined && object.entity !== null)
      ? EntityProto.fromPartial(object.entity)
      : undefined;
    message.entityID = object.entityID ?? undefined;
    message.entityIDList = (object.entityIDList !== undefined && object.entityIDList !== null)
      ? IntListProto.fromPartial(object.entityIDList)
      : undefined;
    message.entityList = (object.entityList !== undefined && object.entityList !== null)
      ? EntityListProto.fromPartial(object.entityList)
      : undefined;
    message.floatList = (object.floatList !== undefined && object.floatList !== null)
      ? FloatListProto.fromPartial(object.floatList)
      : undefined;
    message.intValue = object.intValue ?? undefined;
    message.intList = (object.intList !== undefined && object.intList !== null)
      ? IntListProto.fromPartial(object.intList)
      : undefined;
    message.rawData = object.rawData ?? undefined;
    message.stringValue = object.stringValue ?? undefined;
    message.stringList = (object.stringList !== undefined && object.stringList !== null)
      ? StrListProto.fromPartial(object.stringList)
      : undefined;
    return message;
  },
};

function createBaseStrListProto(): StrListProto {
  return { values: [] };
}

export const StrListProto: MessageFns<StrListProto> = {
  encode(message: StrListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.values) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StrListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStrListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.values.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StrListProto>, I>>(base?: I): StrListProto {
    return StrListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StrListProto>, I>>(object: I): StrListProto {
    const message = createBaseStrListProto();
    message.values = object.values?.map((e) => e) || [];
    return message;
  },
};

function createBaseIntListProto(): IntListProto {
  return { values: [] };
}

export const IntListProto: MessageFns<IntListProto> = {
  encode(message: IntListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.values) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.values.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<IntListProto>, I>>(base?: I): IntListProto {
    return IntListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntListProto>, I>>(object: I): IntListProto {
    const message = createBaseIntListProto();
    message.values = object.values?.map((e) => e) || [];
    return message;
  },
};

function createBaseFloatListProto(): FloatListProto {
  return { values: [] };
}

export const FloatListProto: MessageFns<FloatListProto> = {
  encode(message: FloatListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.values) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FloatListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFloatListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.values.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FloatListProto>, I>>(base?: I): FloatListProto {
    return FloatListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FloatListProto>, I>>(object: I): FloatListProto {
    const message = createBaseFloatListProto();
    message.values = object.values?.map((e) => e) || [];
    return message;
  },
};

function createBaseIntMatrixProto(): IntMatrixProto {
  return { values: [] };
}

export const IntMatrixProto: MessageFns<IntMatrixProto> = {
  encode(message: IntMatrixProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.values) {
      IntListProto.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IntMatrixProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIntMatrixProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.values.push(IntListProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<IntMatrixProto>, I>>(base?: I): IntMatrixProto {
    return IntMatrixProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IntMatrixProto>, I>>(object: I): IntMatrixProto {
    const message = createBaseIntMatrixProto();
    message.values = object.values?.map((e) => IntListProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseValueProto(): ValueProto {
  return {
    defined: false,
    intValue: undefined,
    boolValue: undefined,
    doubleValue: undefined,
    byteList: undefined,
    intList: undefined,
    intMatrix: undefined,
    edgeList: undefined,
    point2D: undefined,
  };
}

export const ValueProto: MessageFns<ValueProto> = {
  encode(message: ValueProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.defined !== false) {
      writer.uint32(8).bool(message.defined);
    }
    if (message.intValue !== undefined) {
      writer.uint32(16).int32(message.intValue);
    }
    if (message.boolValue !== undefined) {
      writer.uint32(24).bool(message.boolValue);
    }
    if (message.doubleValue !== undefined) {
      writer.uint32(33).double(message.doubleValue);
    }
    if (message.byteList !== undefined) {
      writer.uint32(42).bytes(message.byteList);
    }
    if (message.intList !== undefined) {
      IntListProto.encode(message.intList, writer.uint32(50).fork()).join();
    }
    if (message.intMatrix !== undefined) {
      IntMatrixProto.encode(message.intMatrix, writer.uint32(58).fork()).join();
    }
    if (message.edgeList !== undefined) {
      EdgeListProto.encode(message.edgeList, writer.uint32(66).fork()).join();
    }
    if (message.point2D !== undefined) {
      Point2DProto.encode(message.point2D, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValueProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValueProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.defined = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.intValue = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.boolValue = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.doubleValue = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.byteList = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.intList = IntListProto.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.intMatrix = IntMatrixProto.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.edgeList = EdgeListProto.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.point2D = Point2DProto.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ValueProto>, I>>(base?: I): ValueProto {
    return ValueProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValueProto>, I>>(object: I): ValueProto {
    const message = createBaseValueProto();
    message.defined = object.defined ?? false;
    message.intValue = object.intValue ?? undefined;
    message.boolValue = object.boolValue ?? undefined;
    message.doubleValue = object.doubleValue ?? undefined;
    message.byteList = object.byteList ?? undefined;
    message.intList = (object.intList !== undefined && object.intList !== null)
      ? IntListProto.fromPartial(object.intList)
      : undefined;
    message.intMatrix = (object.intMatrix !== undefined && object.intMatrix !== null)
      ? IntMatrixProto.fromPartial(object.intMatrix)
      : undefined;
    message.edgeList = (object.edgeList !== undefined && object.edgeList !== null)
      ? EdgeListProto.fromPartial(object.edgeList)
      : undefined;
    message.point2D = (object.point2D !== undefined && object.point2D !== null)
      ? Point2DProto.fromPartial(object.point2D)
      : undefined;
    return message;
  },
};

function createBasePropertyProto(): PropertyProto {
  return {
    urn: 0,
    defined: false,
    intValue: undefined,
    boolValue: undefined,
    doubleValue: undefined,
    byteList: undefined,
    intList: undefined,
    intMatrix: undefined,
    edgeList: undefined,
    point2D: undefined,
  };
}

export const PropertyProto: MessageFns<PropertyProto> = {
  encode(message: PropertyProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.urn !== 0) {
      writer.uint32(8).int32(message.urn);
    }
    if (message.defined !== false) {
      writer.uint32(16).bool(message.defined);
    }
    if (message.intValue !== undefined) {
      writer.uint32(24).int32(message.intValue);
    }
    if (message.boolValue !== undefined) {
      writer.uint32(32).bool(message.boolValue);
    }
    if (message.doubleValue !== undefined) {
      writer.uint32(41).double(message.doubleValue);
    }
    if (message.byteList !== undefined) {
      writer.uint32(50).bytes(message.byteList);
    }
    if (message.intList !== undefined) {
      IntListProto.encode(message.intList, writer.uint32(58).fork()).join();
    }
    if (message.intMatrix !== undefined) {
      IntMatrixProto.encode(message.intMatrix, writer.uint32(66).fork()).join();
    }
    if (message.edgeList !== undefined) {
      EdgeListProto.encode(message.edgeList, writer.uint32(74).fork()).join();
    }
    if (message.point2D !== undefined) {
      Point2DProto.encode(message.point2D, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PropertyProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePropertyProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.urn = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.defined = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.intValue = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.boolValue = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.doubleValue = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.byteList = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.intList = IntListProto.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.intMatrix = IntMatrixProto.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.edgeList = EdgeListProto.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.point2D = Point2DProto.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PropertyProto>, I>>(base?: I): PropertyProto {
    return PropertyProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PropertyProto>, I>>(object: I): PropertyProto {
    const message = createBasePropertyProto();
    message.urn = object.urn ?? 0;
    message.defined = object.defined ?? false;
    message.intValue = object.intValue ?? undefined;
    message.boolValue = object.boolValue ?? undefined;
    message.doubleValue = object.doubleValue ?? undefined;
    message.byteList = object.byteList ?? undefined;
    message.intList = (object.intList !== undefined && object.intList !== null)
      ? IntListProto.fromPartial(object.intList)
      : undefined;
    message.intMatrix = (object.intMatrix !== undefined && object.intMatrix !== null)
      ? IntMatrixProto.fromPartial(object.intMatrix)
      : undefined;
    message.edgeList = (object.edgeList !== undefined && object.edgeList !== null)
      ? EdgeListProto.fromPartial(object.edgeList)
      : undefined;
    message.point2D = (object.point2D !== undefined && object.point2D !== null)
      ? Point2DProto.fromPartial(object.point2D)
      : undefined;
    return message;
  },
};

function createBasePoint2DProto(): Point2DProto {
  return { X: 0, Y: 0 };
}

export const Point2DProto: MessageFns<Point2DProto> = {
  encode(message: Point2DProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.X !== 0) {
      writer.uint32(9).double(message.X);
    }
    if (message.Y !== 0) {
      writer.uint32(17).double(message.Y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Point2DProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePoint2DProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.X = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.Y = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Point2DProto>, I>>(base?: I): Point2DProto {
    return Point2DProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Point2DProto>, I>>(object: I): Point2DProto {
    const message = createBasePoint2DProto();
    message.X = object.X ?? 0;
    message.Y = object.Y ?? 0;
    return message;
  },
};

function createBaseEntityProto(): EntityProto {
  return { urn: 0, entityID: 0, properties: [] };
}

export const EntityProto: MessageFns<EntityProto> = {
  encode(message: EntityProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.urn !== 0) {
      writer.uint32(8).int32(message.urn);
    }
    if (message.entityID !== 0) {
      writer.uint32(16).int32(message.entityID);
    }
    for (const v of message.properties) {
      PropertyProto.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.urn = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.entityID = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.properties.push(PropertyProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EntityProto>, I>>(base?: I): EntityProto {
    return EntityProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityProto>, I>>(object: I): EntityProto {
    const message = createBaseEntityProto();
    message.urn = object.urn ?? 0;
    message.entityID = object.entityID ?? 0;
    message.properties = object.properties?.map((e) => PropertyProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEntityListProto(): EntityListProto {
  return { entities: [] };
}

export const EntityListProto: MessageFns<EntityListProto> = {
  encode(message: EntityListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entities) {
      EntityProto.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entities.push(EntityProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EntityListProto>, I>>(base?: I): EntityListProto {
    return EntityListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityListProto>, I>>(object: I): EntityListProto {
    const message = createBaseEntityListProto();
    message.entities = object.entities?.map((e) => EntityProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfigProto(): ConfigProto {
  return { data: {} };
}

export const ConfigProto: MessageFns<ConfigProto> = {
  encode(message: ConfigProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.data).forEach(([key, value]: [string, string]) => {
      ConfigProto_DataEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = ConfigProto_DataEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.data[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ConfigProto>, I>>(base?: I): ConfigProto {
    return ConfigProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConfigProto>, I>>(object: I): ConfigProto {
    const message = createBaseConfigProto();
    message.data = (globalThis.Object.entries(object.data ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseConfigProto_DataEntry(): ConfigProto_DataEntry {
  return { key: "", value: "" };
}

export const ConfigProto_DataEntry: MessageFns<ConfigProto_DataEntry> = {
  encode(message: ConfigProto_DataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigProto_DataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigProto_DataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ConfigProto_DataEntry>, I>>(base?: I): ConfigProto_DataEntry {
    return ConfigProto_DataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConfigProto_DataEntry>, I>>(object: I): ConfigProto_DataEntry {
    const message = createBaseConfigProto_DataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseEdgeListProto(): EdgeListProto {
  return { edges: [] };
}

export const EdgeListProto: MessageFns<EdgeListProto> = {
  encode(message: EdgeListProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.edges) {
      EdgeProto.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EdgeListProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEdgeListProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.edges.push(EdgeProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EdgeListProto>, I>>(base?: I): EdgeListProto {
    return EdgeListProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EdgeListProto>, I>>(object: I): EdgeListProto {
    const message = createBaseEdgeListProto();
    message.edges = object.edges?.map((e) => EdgeProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEdgeProto(): EdgeProto {
  return { startX: 0, startY: 0, endX: 0, endY: 0, neighbour: 0 };
}

export const EdgeProto: MessageFns<EdgeProto> = {
  encode(message: EdgeProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startX !== 0) {
      writer.uint32(8).int32(message.startX);
    }
    if (message.startY !== 0) {
      writer.uint32(16).int32(message.startY);
    }
    if (message.endX !== 0) {
      writer.uint32(24).int32(message.endX);
    }
    if (message.endY !== 0) {
      writer.uint32(32).int32(message.endY);
    }
    if (message.neighbour !== 0) {
      writer.uint32(40).int32(message.neighbour);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EdgeProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEdgeProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.startX = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startY = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endX = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endY = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.neighbour = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EdgeProto>, I>>(base?: I): EdgeProto {
    return EdgeProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EdgeProto>, I>>(object: I): EdgeProto {
    const message = createBaseEdgeProto();
    message.startX = object.startX ?? 0;
    message.startY = object.startY ?? 0;
    message.endX = object.endX ?? 0;
    message.endY = object.endY ?? 0;
    message.neighbour = object.neighbour ?? 0;
    return message;
  },
};

function createBaseChangeSetProto(): ChangeSetProto {
  return { changes: [], deletes: [] };
}

export const ChangeSetProto: MessageFns<ChangeSetProto> = {
  encode(message: ChangeSetProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.changes) {
      ChangeSetProto_EntityChangeProto.encode(v!, writer.uint32(10).fork()).join();
    }
    writer.uint32(18).fork();
    for (const v of message.deletes) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeSetProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeSetProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.changes.push(ChangeSetProto_EntityChangeProto.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.deletes.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.deletes.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChangeSetProto>, I>>(base?: I): ChangeSetProto {
    return ChangeSetProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeSetProto>, I>>(object: I): ChangeSetProto {
    const message = createBaseChangeSetProto();
    message.changes = object.changes?.map((e) => ChangeSetProto_EntityChangeProto.fromPartial(e)) || [];
    message.deletes = object.deletes?.map((e) => e) || [];
    return message;
  },
};

function createBaseChangeSetProto_EntityChangeProto(): ChangeSetProto_EntityChangeProto {
  return { entityID: 0, urn: 0, properties: [] };
}

export const ChangeSetProto_EntityChangeProto: MessageFns<ChangeSetProto_EntityChangeProto> = {
  encode(message: ChangeSetProto_EntityChangeProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityID !== 0) {
      writer.uint32(8).int32(message.entityID);
    }
    if (message.urn !== 0) {
      writer.uint32(16).int32(message.urn);
    }
    for (const v of message.properties) {
      PropertyProto.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeSetProto_EntityChangeProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeSetProto_EntityChangeProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.entityID = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.urn = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.properties.push(PropertyProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChangeSetProto_EntityChangeProto>, I>>(
    base?: I,
  ): ChangeSetProto_EntityChangeProto {
    return ChangeSetProto_EntityChangeProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeSetProto_EntityChangeProto>, I>>(
    object: I,
  ): ChangeSetProto_EntityChangeProto {
    const message = createBaseChangeSetProto_EntityChangeProto();
    message.entityID = object.entityID ?? 0;
    message.urn = object.urn ?? 0;
    message.properties = object.properties?.map((e) => PropertyProto.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
